# Generated by Django 4.2.3 on 2023-07-07 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_True', models.PositiveIntegerField(default='1')),
                ('title', models.CharField(max_length=100)),
                ('original_anime', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('grade', models.FloatField(blank=True, default='0')),
                ('grade_time', models.PositiveIntegerField(blank=True, default='0')),
                ('Number_episodes', models.CharField(blank=True, max_length=100)),
                ('Number_seasons', models.CharField(blank=True, max_length=100)),
                ('Number_films', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField(blank=True, default='0')),
                ('Plot_Grade', models.PositiveIntegerField(default='0')),
                ('Animation_Grade', models.PositiveIntegerField(default='0')),
                ('Characters_Grade', models.PositiveIntegerField(default='0')),
                ('World_Grade', models.PositiveIntegerField(default='0')),
                ('IMHO_Grade', models.PositiveIntegerField(default='0')),
                ('photo', models.ImageField(upload_to='articles/')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ganres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slag', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='articles/')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звезды рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Studios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slag', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('anime', models.ForeignKey(on_delete=django.db.models.fields.CharField, to='karamba.anime', verbose_name='Аниме')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karamba.ratingstar', verbose_name='Звезда')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('text', models.TextField(max_length=100, verbose_name='Сообщение')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karamba.anime', verbose_name='Аниме')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='karamba.comment', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='AnimeShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='shots/', verbose_name='')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karamba.anime', verbose_name='Аниме')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='ganre',
            field=models.ManyToManyField(blank=True, related_name='anime_ganres', to='karamba.ganres'),
        ),
        migrations.AddField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anime_studios', to='karamba.studios'),
        ),
    ]
