# Generated by Django 4.2.3 on 2023-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karamba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOngiing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slag', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='check_Ongoing',
            field=models.ManyToManyField(blank=True, default='Вышел', related_name='anime_ganres', to='karamba.checkongiing'),
        ),
    ]
